apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-words
  labels:
    app: reverse-words
spec:
  template:
    spec:
      containers:
      - name: reverse-words
        image: registry.cn-hangzhou.aliyuncs.com/haoshuwei24/reversewords:v0.0.3
        env:
        - name: RELEASE
          value: "Preproduction release"
        - $patch: replace
